### ISSUE TITLE
tippy.css 404

### ISSUE THREAD

**Issue by Core00077** [RichardYan314/hexo-pandoc-tippy#1]
非常感谢大佬开发，一直苦于pandoc渲染器没有好用的可悬浮的tippy。

不过有些问题（不做前端，有些不太懂）：

- 安好了启用后一直没有找到css/tippy.css的资源，看得出来能调tippy.js（悬浮框可以使用），但对应的css似乎无法加载（我也没有tippy.css，emmmmm主要是也不知道是哪个文件引的tippy.css就有点僵）。后来在您博客下[footnote](https://richardyan.site/Footnote-Test/)找到了您写的tippy.css，放在了css/tippy.css，然而还是没出您css的效果，审查元素发现这些元素并没有对应的class（所以css选择器选不到），具体情况可以看[我的这篇博客](https://coreja.com/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/2019/03/LaTex%E5%AD%A6%E4%B9%A0/)

- （上面是没有在_config.yml配置tippy但配置了pandoc）看见readme里有提到tippy配置，tippy下theme_file不管是填tippy.css还是css/tippy.css还是/css/tippy.css，都会报错
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'tippy.css'
Emitted 'error' event at:
    at ReadStream.data.on.err (/home/core/Documents/hexo_blogs/node_modules/hexo/lib/hexo/router.js:145:14)
    at ReadStream.emit (events.js:197:13)
    at /home/core/Documents/hexo_blogs/node_modules/graceful-fs/graceful-fs.js:207:14
    at /home/core/Documents/hexo_blogs/node_modules/graceful-fs/graceful-fs.js:258:16
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
```

PS: 您的readme关于tippy文档customization theme的url更新了，新的是[这个](https://atomiks.github.io/tippyjs/#themes)

PPS：非常感谢您的开源贡献，个人博客一直很希望有这个注脚功能，感谢大佬！El Psy Congroo

**Comment by Core00077** [comment]
抱歉打扰大佬了！第二个问题我自己解决了，那个配置旁注释写的root目录指的是hexo的根目录，而非网站站点的根目录，改好了之后第一个问题也迎刃而解了。

不过[我的这篇博客](https://coreja.com/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/2019/03/LaTex%E5%AD%A6%E4%B9%A0/)里，虽然引了您的tippy.css，但是很奇怪的是背景色依然没有修改为红色，我猜大概是我css的问题，回头再看看吧。

再次感谢大佬！

PS：希望可以有鼠标移动到注脚内容的时候，注脚可以不消失的功能（大概在tippy里有，我自己去看！谢谢大佬），这样可以点击某些注脚里的链接嘻嘻嘻。跪谢大佬！

**Comment by Core00077** [comment]
在tippy的官方文档找到了，只要在站点的_config.yml的tippy下加一行`interactive: true`即可完成前面的功能，冒昧打扰实在抱歉，此issue关闭了。El Psy Congroo

**Comment by RichardYan314** [comment]
您好，非常感谢您喜欢这个小插件，也感谢您提出 issue。

十分高兴您在我回复之前就已经解决了问题。方才在您的博客里看到，您实现了十分漂亮的 footnote。

关于新的 url 以及相对路径的根目录，我已经在文档里增加了说明。关于可点击链接的 interactive tooltip，这正是开发此插件引入 tippy 的原因：市面上其他的 tooltip 都不支持带 HTML 标签的富文本。

由于变更仅涉及到文档而非代码，所以您没有必要更新此插件。

再次感谢您的支持。今后有什么需要也请提 issue。

El Psy Congroo
