### ISSUE TITLE
cheerio导致文本被转换成html实体编码问题

### ISSUE THREAD

**Issue by Core00077** [RichardYan314/hexo-pandoc-tippy#4]
hey大佬又见面了。前不久把hexo的包升级了一趟，发现了你这边cheerio的引入导致的问题。具体如下：**html被转换成了实体编码**
转换前
![image](https://user-images.githubusercontent.com/28624864/62593261-9f991f00-b908-11e9-980a-03ea70fd9ca8.png)
转换后
![image](https://user-images.githubusercontent.com/28624864/62593291-b770a300-b908-11e9-8b74-c1856d15c0e4.png)
这个问题在网页上看不出来任何差别，但是在使用hexo的搜索功能时候，搜索的内容为实体编码。如图：
![image](https://user-images.githubusercontent.com/28624864/62593756-88f3c780-b90a-11e9-9d30-485ff1d4d202.png)

很不凑巧的是我之前遇到过这个问题，当时用这个包导致了[同样的问题](https://github.com/crimx/hexo-filter-github-emojis/issues/17)
我当时正好有点时间，就改了改代码，提了[pr](https://github.com/crimx/hexo-filter-github-emojis/pull/18)解决了问题 。

目前我退回到了0.2.4版本，博客暂时恢复了。如果需要复现，请提前告知并访问[test.coreja.com](http://test.coreja.com)（因为是用我的笔记本内网穿透用于测试，所以网络稳定性不能保证。但我尽量保证我的笔记本一直online）

**Comment by RichardYan314** [comment]
老实说，我认为在 html 中尽可能多地 escape 字符是个更好的做法，因此我更情愿看到你使用的搜索功能能够识别到实体编码。
虽然基于 hexo 的静态博客通常不受 xss 之苦，然而有时我们还是希望能够强制 escape 某些文本。
考虑下例

test case derived from [issue comment](https://github.com/cheeriojs/cheerio/issues/866#issuecomment-275671893):

markdown
```` markdown
<div>&lt;script&gt;alert(1)&lt;/script&gt;</div>

``` html
<script>alert(2)</script>
```

中文
````

without `{decodeEntities: false}` (current approach):

html
``` html
<div>
    &lt;script&gt;alert(1)&lt;/script&gt;
</div>

<figure class="highlight html"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">&lt;script&gt;alert(2)&lt;/script&gt;</span><br></pre></td></tr></tbody></table></figure>

<p>&#x4E2D;&#x6587;</p>
```

with `{decodeEntities: false}`  (this approach is the worst):

html
``` html
<div>
    <script>alert(1)</script>
</div>

<figure class="highlight html"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><script>alert(2)</script></span><br></pre></td></tr></tbody></table></figure>

<p>中文</p>
```

with [this approach](https://github.com/cheeriojs/cheerio/issues/866#issuecomment-482730997):

html
``` html
<div>
    &lt;script&gt;alert(1)&lt;/script&gt;
</div>

<figure class="highlight html"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">&lt;script&gt;alert(2)&lt;/script&gt;</span><br></pre></td></tr></tbody></table></figure>

<p>中文</p>


```

The central idea of the above approach is "Don't unescape ASCII characters, assuming they're encoded for a good reason".

我把使用第三种方法的更新推到 npm 了，使用的版本号是 `0.4.0-alpha`。
你试试看，要是解决了问题，我再 bump 到正式版本号。
不行的话再重开这个 issue.

**Comment by Core00077** [comment]
问题解决了。
恩这个帖子我当时也参考了。无奈并不太懂一些前端的知识，的确直接一股脑ban掉转义不太好。

不过考虑到当时的做法仅用于转义博客正文中，由`::`包裹的emoji，做法和第三种方式也差不太远。第三种方式是对于文本有针对性的ban掉转义，而我是load的文本以及要转换的emoji限制了它不存在escape。

嘛，至于搜索是next主题自带的，也就懒得折腾了。我也希望它可以，毕竟这是我第二次遇到这个问题了。

顺带一提，我不太喜欢cheerio这种默认就全体decodeEntities: false的风格，我更倾向于你提供的第三种做法，该转义的时候才转。我对比了google还有github，至少用于表意的文字并没有发生转义。想想爬下来一群html编码还得转义回去，想想就麻烦emmmm
